# Site settings
title: Great New Blog Title
author: Alyon Yap
  name: Evan Will
  email: alyonyapp@gmail.co,
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
