# Site settings
title: Great New Blog Title
author: Alyon Yap
  name: Alyon Yap
  email: alyonyapp@gmail.com,
  port
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
